# Change when R support is available on Travis CI
language: python

env:
  - R_LIBS_USER=~/R

# Install dependencies
install:
  - sudo apt-add-repository -y 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install r-base-dev r-cran-xml qpdf texinfo texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - R -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages("selectr", dep = TRUE, repos = "http://cran.rstudio.org")'

# Run package checks
script:
  - make install
  - make check
